// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kznxdeyqygfrrpdbdnny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6bnhkZXlxeWdmcnJwZGJkbm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTgxMTksImV4cCI6MjA2NjUzNDExOX0.qXpSZs1rF3JvOy2jarJuTl3BqhEzB8FqF6GshV8XtVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);